name = input("hello, whats your name?")
print("hi", name)   
age = input("what is your age????????")
print(age,"is a great age to be!")
lesson = input("what is your favorite lesson?")
print(" I also like",lesson, "!")
lessonpt2 = len(lesson)
print(lesson, "has", lessonpt2, "letters!")
teacher = input("who is your teacher?")
print(teacher, "makes me think too hard!")
country = input("what is your country?")
countrypt2 = 
print(countrypt2)
